// <auto-generated />
using System;
using EsparkKartur.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsparkKartur.Infrastructure.Migrations
{
    [DbContext(typeof(EsparkKarturDbContext))]
    [Migration("20251222180018_AuditSystemAdded")]
    partial class AuditSystemAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("EsparkKartur.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EskiDeger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KayıtId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabloAdı")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YeniDeger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("İşlemTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("İşlemTürü")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.FisKargo", b =>
                {
                    b.Property<int>("FisId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FisID");

                    b.Property<int>("KargoFirmaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("KargoID");

                    b.HasKey("FisId", "KargoFirmaId");

                    b.HasIndex("KargoFirmaId");

                    b.ToTable("FisKargo");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.FisUrunleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UrunID");

                    b.Property<int>("FişId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FisID");

                    b.Property<int>("KoliAdet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaketAdet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FişId")
                        .IsUnique();

                    b.ToTable("FisUrunleri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.KargoFirmasi", b =>
                {
                    b.Property<int>("KargoFirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("KargoID");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Durum");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("KargoAdi");

                    b.HasKey("KargoFirmaId");

                    b.ToTable("KargoFirmalari");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("KullaniciID");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AdSoyad");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Durum");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Rol");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Magaza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("MagazaID");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Durum");

                    b.Property<string>("MagazaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Magazalar");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.SevkFisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("FisID");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<string>("FişNumarasi")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FisNumarasi");

                    b.Property<int>("GonderimModu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImzaDosyasi")
                        .HasColumnType("TEXT");

                    b.Property<int>("MagazaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MagazaID");

                    b.Property<int>("OlusturanID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OlusturanID");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeslimAlanAdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TeslimAlan");

                    b.Property<int>("Yon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FişNumarasi")
                        .IsUnique();

                    b.HasIndex("MagazaId");

                    b.HasIndex("OlusturanID");

                    b.ToTable("SevkFisleri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.AuditTrail", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.FisKargo", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.SevkFisi", "SevkFisi")
                        .WithMany("Kargoİlişkileri")
                        .HasForeignKey("FisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsparkKartur.Domain.Entities.KargoFirmasi", "KargoFirmasi")
                        .WithMany("FişKargoİlişkileri")
                        .HasForeignKey("KargoFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KargoFirmasi");

                    b.Navigation("SevkFisi");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.FisUrunleri", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.SevkFisi", "SevkFisi")
                        .WithOne("UrunDetaylari")
                        .HasForeignKey("EsparkKartur.Domain.Entities.FisUrunleri", "FişId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SevkFisi");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.SevkFisi", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.Magaza", "Magaza")
                        .WithMany("SevkFisleri")
                        .HasForeignKey("MagazaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsparkKartur.Domain.Entities.Kullanici", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magaza");

                    b.Navigation("Olusturan");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.KargoFirmasi", b =>
                {
                    b.Navigation("FişKargoİlişkileri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Magaza", b =>
                {
                    b.Navigation("SevkFisleri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.SevkFisi", b =>
                {
                    b.Navigation("Kargoİlişkileri");

                    b.Navigation("UrunDetaylari")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
