// <auto-generated />
using System;
using EsparkKartur.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsparkKartur.Infrastructure.Migrations
{
    [DbContext(typeof(EsparkKarturDbContext))]
    [Migration("20251216122506_FixFkOlusturan")]
    partial class FixFkOlusturan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("EsparkKartur.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EskiDeger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KayıtId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TabloAdı")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YeniDeger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("İşlemTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("İşlemTürü")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.FişKargoİlişkisi", b =>
                {
                    b.Property<int>("FişId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KargoFirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtanmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("SevkFisiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FişId", "KargoFirmaId");

                    b.HasIndex("KargoFirmaId");

                    b.ToTable("FişKargoİlişkileri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.FişUrunleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FişId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KoliAdet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaketAdet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FişId")
                        .IsUnique();

                    b.ToTable("FişUrunleri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.KargoFirmasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KargoFirmalari");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Mağaza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MagazaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MagazaKodu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MagazaKodu")
                        .IsUnique();

                    b.ToTable("Magazalar");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Sefer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BitisZamani")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeferYonu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("Seferler");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.SevkFisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("FisID");

                    b.Property<bool>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<string>("FişNumarasi")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FisNumarasi");

                    b.Property<string>("GonderimModu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImzaDosyasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MagazaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MagazaID");

                    b.Property<int>("OlusturanID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OlusturanID");

                    b.Property<int>("SeferId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SeferID");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeslimAlanAdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TeslimAlan");

                    b.Property<string>("Yon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FişNumarasi")
                        .IsUnique();

                    b.HasIndex("MagazaId");

                    b.HasIndex("OlusturanID");

                    b.HasIndex("SeferId");

                    b.ToTable("SevkFisleri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Tarife", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<int>("MagazaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TarifeAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TarifeTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tarifeler");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.AuditTrail", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.FişKargoİlişkisi", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.SevkFisi", "SevkFisi")
                        .WithMany("Kargoİlişkileri")
                        .HasForeignKey("FişId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsparkKartur.Domain.Entities.KargoFirmasi", "KargoFirmasi")
                        .WithMany("FişKargoİlişkileri")
                        .HasForeignKey("KargoFirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KargoFirmasi");

                    b.Navigation("SevkFisi");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.FişUrunleri", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.SevkFisi", "SevkFisi")
                        .WithOne("UrunDetaylari")
                        .HasForeignKey("EsparkKartur.Domain.Entities.FişUrunleri", "FişId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SevkFisi");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Kullanici", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Sefer", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.Kullanici", "Personel")
                        .WithMany("Seferler")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.SevkFisi", b =>
                {
                    b.HasOne("EsparkKartur.Domain.Entities.Mağaza", "Magaza")
                        .WithMany("SevkFisleri")
                        .HasForeignKey("MagazaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsparkKartur.Domain.Entities.Kullanici", "Olusturan")
                        .WithMany()
                        .HasForeignKey("OlusturanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsparkKartur.Domain.Entities.Sefer", "Sefer")
                        .WithMany("SevkFisleri")
                        .HasForeignKey("SeferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magaza");

                    b.Navigation("Olusturan");

                    b.Navigation("Sefer");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.KargoFirmasi", b =>
                {
                    b.Navigation("FişKargoİlişkileri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("Seferler");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Mağaza", b =>
                {
                    b.Navigation("SevkFisleri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.Sefer", b =>
                {
                    b.Navigation("SevkFisleri");
                });

            modelBuilder.Entity("EsparkKartur.Domain.Entities.SevkFisi", b =>
                {
                    b.Navigation("Kargoİlişkileri");

                    b.Navigation("UrunDetaylari")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
